apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: agent-rest-api
build:
  artifacts:
  - image: agent-rest-api
    context: .
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - k8s/deployment.yaml
deploy:
  kubectl: {}
portForward:
- resourceType: service
  resourceName: agent-rest-api
  port: 80
  localPort: 8000
